sonar.projectKey=oop-group-13-border-layout-task
sonar.projectName=Border Layout Task - OOP Group 13
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=squ_fa7fbd1d4a16825e6bbea6a9d4af774a0f1a0d2d

sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/.idea/**,**/*.xml,**/*.json,**/*.md,**/*.iml,**/*.properties

sonar.java.binaries=.

sonar.log.level=INFO
sonar.links.scm=https://github.com/OOP-group-13/Border-Layout-Task
